# docker-compose.yml
version: '3'
services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    volumes:
      - 'money-app-pg-data:/var/lib/postgresql/data'
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
volumes:
  money-app-pg-data:
